<?php

/*
	Copyright (C) GPLv2 2011-2018 Nathan A. Mourey II <nmoureyii@gmail.com>

	Note: The db access methods are not as clean as they could
	be due to useing an older version of PHP.

	Function: The porgram basicly is a web front end for the
	following SQL commands:

	CREATE USER 'USER_NAME'@'localhost' IDENTIFIED BY 'PASS'; 
	GRANT ALL PRIVILEGES ON DB_NAME.* TO 'USER_NAME'@'localhost'; 

	Change the global variables below to suite your configuration.
	The only one that really should need changing is $password.

*/

// global vars.
$hostname = "localhost"; 
$database = "mysql";
$username = "root";
$password = "";

/* List of users, files or directories to remove from output.   Keep the following format.
 * For example to add another item to exclude the following line would look
 * like :  $remove_list = "/map32.exe|perl|nmoureyii/";
 * Note: The list of users in generated by reading the /home directorie.  If you have
 * anything in the /home directorie that you want remove add it to the $remove_list below.
 */

$remove_list = "/guest|nfs|map32\.exe|perl|toor|lost\+found|unix|aquota*/";

## Successfull inclusion.

/*******************  You should not need to go below this line. **********************/

function db_connect(){
	global $hostname;
	global $database;
	global $username; 
	global $password;

	$result = new mysqli($hostname, $username, $password, $database);

        if ( !$result ) {
                throw new Exception('Could not connect to the database');
        } else {
                return $result;
        }
}

function username_to_fullname($name = ""){
	$userinfo = posix_getpwnam($name);
	return $userinfo['gecos'];
}

function get_user_list(){
	global $remove_list;


	$html = "<ul id=\"user_list\">";
	$list_of_names = array();


	// get everything in /home and put into an array.
	$state = "/home/";
	$dir = opendir($state);
	while (false !== ($file = readdir($dir)) ){
		$list_of_names[] = $file;
	}
	closedir($dir);

	// alphabeticalize and expand login to full name.
	sort($list_of_names);
	foreach ($list_of_names as $name){
		if ($name != "." && $name != ".."){
			// Removes names listed in the remove list above. 
			if ( !preg_match($remove_list, $name) ) {
				$fname = username_to_fullname($name);
				$html .= "<li ><a href=\"main.php?name=$name\" target=\"form\">$fname</a></li>\n";
			}
		}
	}
	$html .= "</ul>";
	return $html;
}


function check_user($user){
	$conn = db_connect();
	$q = sprintf("SELECT User FROM user WHERE User = '%s'", $user);
	// print "<h3>$q</h3>";
	$result = $conn->query($q) or die('Query failed: ' . mysql_error());
	return $result->num_rows;
}

function del_user($user){
	$conn = db_connect();
	$q = sprintf("DROP USER '%s'@'localhost'", $user); 
	// print "<h3>$q</h3>";
	$result = $conn->query($q) or die('Query failed: ' . mysql_error());
	$q = "FLUSH PRIVILEGES";
	// print "<h3>$q</h3>";
	$result = $conn->query($q) or die('Query failed: ' . mysql_error());
	return 1; 
}

function add_user($user, $pass){
	$conn = db_connect();
	$q = sprintf("CREATE USER '%s'@'localhost' IDENTIFIED BY '%s'", $user, $pass); 
	// print "<h3>$q</h3>";
	$result = $conn->query($q) or die('Query failed: ' . mysql_error());
	$q = "FLUSH PRIVILEGES";
	// print "<h3>$q</h3>";
	$result = $conn->query($q) or die('Query failed: ' . mysql_error());
	return 1;
}

function add_db($db, $user){
	$conn = db_connect();
	$q = sprintf("GRANT ALL PRIVILEGES ON `%s\_%%`.* TO '%s'@'localhost'", $db, $user); 
	$result = $conn->query($q) or die('Query failed: ' . mysql_error());
	// print "<h3>$q</h3>";
	return $result->num_rows;
}

function update_pass($user, $pass){
	$conn = db_connect();
	$q = sprintf("UPDATE user SET password=PASSWORD('%s') WHERE User = '%s'", $pass, $user); 
	// print "<h3>$q</h3>";
	$result = $conn->query($q) or die('Query failed: ' . mysql_error());
	return $result->num_rows;
}

function fix_pass($str){
	$temp = str_replace(" ",'',$str);	
	return $temp;
}


function fix_str($str){
	$replace = array("!","@","#","$","%","^","&","*","(",")"," ");
	$temp = str_replace($replace,'',$str);	
	return $temp;
}

function make_string_added_to_db($name = "", $db_name = ""){
	$fname = username_to_fullname($name);
	$u ="_";

	$added = "<div id=\"add_div\"><span id=\"added\">MySQL user <span id=\"name\">$name</span> has all privlages 
		 for database <span id=\"db_name\">$db_name$u*</span><br/><span id=\"name\">$fname</span> can create and drop 
		 any database that begins with <span id=\"db_name\">$db_name$u</span>.</span></div>";

	return $added;
}

/*
	function found here:
		http://www.totallyphp.co.uk/code/create_a_random_password.htm
*/
function gen_pass() { 
    $chars = "abcdefghijkmnopqrstuvwxyz023456789"; 
    srand((double)microtime()*1000000); 
    $i = 0; 
    $pass = ''; 

    while ($i <= 7) { 
        $num = rand() % 33; 
        $tmp = substr($chars, $num, 1); 
        $pass = $pass . $tmp; 
        $i++; 
    } 
    return $pass; 
} 

/* Returns the form for the user to fill out. */
function print_form($user_in_db = "", $uinfo="", $name = "", $password_notice = ""){
	$pass = gen_pass();

$form = "
<div id=\"form_div\">
<fieldset>
<legend><span id=\"leg\">Adding Database User : $uinfo</span></legend>
<form action=\"main.php?update=1\" method=\"post\">
        <table id=\"change_form\">
        <tr><td>Database</td><td><input type=\"text\" name=\"db_name\" value=\"$name\" size=\"25\"></td></tr>
        <tr><td>Password*</td><td><input type=\"text\" name=\"pass\" value=\"$pass\" size=\"25\"><input type=\"hidden\" name=\"name\" value=\"$name\"/></td></tr>
        <tr><td colspan=\"2\"><input type=\"submit\" value=\"Update User Information Now.\"></td></tr>
        </table>
</form>
$password_notice
</fieldset>
$user_in_db
</div></div>";

	return $form;
}


#### Strings. etc.
$error = "<div id=\"error_div\"><span id=\"error_mesg\">Please go back and check that you have entered a database name and password.</span></div>";
$welcome = "<div id=\"welcome_div\"><span id=\"added\">Welcome. Click name to left to begin. <p/>Always click the browsers reload button after adding Unix user accounts.</span></div>";
$password_notice = "<div><span id=\"pass_notice\">* Please take note of password.</span></div>";
$in_db = "<div><span id=\"in_db\">User is already in the database.</span></div>";
$back = "<div id=\"back\"><span id=\"back_span\"><a href=\"index.php\" target=\"_top\">Return to Welcome page.</a><p/>Or click name to left to continue.</span></div>";

?>
